### PR TITLE
A first update of the french translation

### PR DESCRIPTION
**Pull request by MrMargouillat**
Thanks for your work. ;-)

### CODE REVIEW

**Comment by cuzbog** [comment]
Erreur\* :)

**Comment by MrMargouillat** [comment]
C'est corrigé ;-)

**Comment by cuzbog** [comment]
Merci beaucoup :)

**Comment by MrMargouillat** [comment]
Il manque plus que celà sois intégré ;-)

**Comment by iBelieve** [comment]
We're now using Qt translations, so this won't work anymore. Feel free to make translations for the new Qt translations system. Thanks!

**Pull request closed without merging**
